export const REQUEST_MEASURES = 'REQUEST_MEASURES';
export const REQUEST_MEASURES_FULFILLED = 'REQUEST_MEASURES_FULFILLED';
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const REQUEST_USER_INFO_FULFILLED = 'REQUEST_USER_INFO_FULFILLED';
export const REQUEST_NEW_QUALITY_REPORT = 'REQUEST_NEW_QUALITY_REPORT';
export const POST_NEW_QUALITY_REPORT = 'POST_NEW_QUALITY_REPORT';
export const POST_NEW_QUALITY_REPORT_FULFILLED = 'POST_NEW_QUALITY_REPORT_FULFILLED';
export const SELECT_MEASURE = 'SELECT_MEASURE';
