// ------------------------- MEASURE --------------------------------------- //

export const FETCH_MEASURES = 'FETCH_MEASURES';
export const FETCH_MEASURES_FULFILLED = 'FETCH_MEASURES_FULFILLED';
export const FETCH_MEASURES_RESOLVED = 'FETCH_MEASURES_RESOLVED';
export const SELECT_MEASURE = 'SELECT_MEASURE';
export const UNSELECT_MEASURE = 'UNSELECT_MEASURE';

// ------------------------- PATIENT --------------------------------------- //

export const FETCH_PATIENT_COUNT = 'FETCH_PATIENT_COUNT';
export const FETCH_PATIENT_COUNT_FULFILLED = 'FETCH_PATIENT_COUNT_FULFILLED';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_FULFILLED = 'FETCH_USER_INFO_FULFILLED';

// ------------------------- QUALITY REPORT -------------------------------- //

export const FETCH_QUALITY_REPORT = 'FETCH_QUALITY_REPORT';
export const FETCH_QUALITY_REPORT_FULFILLED = 'FETCH_QUALITY_REPORT_FULFILLED';
export const FETCH_NEW_QUALITY_REPORT = 'FETCH_NEW_QUALITY_REPORT';
export const POST_NEW_QUALITY_REPORT = 'POST_NEW_QUALITY_REPORT';
export const POST_NEW_QUALITY_REPORT_FULFILLED = 'POST_NEW_QUALITY_REPORT_FULFILLED';

// ------------------------- POPULATION ------------------------------------ //

export const FETCH_INITIAL_PATIENT_POPULATION = 'FETCH_INITIAL_PATIENT_POPULATION';
export const FETCH_NUMERATOR_POPULATION = 'FETCH_NUMERATOR_POPULATION';
export const FETCH_DENOMINATOR_POPULATION = 'FETCH_DENOMINATOR_POPULATION';
export const FETCH_OUTLIER_POPULATION = 'FETCH_OUTLIER_POPULATION';
export const FETCH_INITIAL_PATIENT_POPULATION_FULFILLED = 'FETCH_INITIAL_PATIENT_POPULATION_FULFILLED';
export const FETCH_NUMERATOR_POPULATION_FULFILLED = 'FETCH_NUMERATOR_POPULATION_FULFILLED';
export const FETCH_DENOMINATOR_POPULATION_FULFILLED = 'FETCH_DENOMINATOR_POPULATION_FULFILLED';
export const FETCH_OUTLIER_POPULATION_FULFILLED = 'FETCH_OUTLIER_POPULATION_FULFILLED';
export const FETCH_INITIAL_PATIENT_POPULATION_RESOLVED = 'FETCH_INITIAL_PATIENT_POPULATION_RESOLVED';
export const FETCH_NUMERATOR_POPULATION_RESOLVED = 'FETCH_NUMERATOR_POPULATION_RESOLVED';
export const FETCH_DENOMINATOR_POPULATION_RESOLVED = 'FETCH_DENOMINATOR_POPULATION_RESOLVED';
export const FETCH_OUTLIER_POPULATION_RESOLVED = 'FETCH_OUTLIER_POPULATION_RESOLVED';
